# Site settings
site: Çağatay Güley
title: Çağatay Güley - Maden Mühendisi
keywords: maden, mühendis, cagatay guley, cagatay, guley, mining engineer, mining engineering, mining industry, mining technology
description: >-
  As a passionate mining engineer, I will unveil mineral riches and innovative solutions, taking us towards new horizons.
lang: en-US
timezone:  Europe/Istanbul
logo: assets/images/logo.svg
google_tag: GTM-T863VL7J
# discus-identifier:  

# Author settings
author:
  name: Çağatay Güley
  bio: "Maden Mühendisi ⛏️ <br> @ore2b Kurucusu"
  picture: assets/images/profile.svg
  github: guleyc
  # twitter: 
  # facebook: 
  # instagram: 
  # youtube: 
  linkedin: guleyc
  email: cagatay@guley.com.tr


# URL settings
url: "https://guley.com.tr"
baseurl: ""
permalink: pretty
repo: https://github.com/guleyc

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-relative-links

paginate: 3
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false

jekyll-archives:
  enabled:
    - tags
    - categories
  layout: archive
  permalinks:
    tag: /tag/:name/
    category: /category/:name/